### PR TITLE
fix: social screen ML Kit dependency and AppNavigation composable scope

### PR DESCRIPTION
**Pull request by cancleeric**
## Summary

Fixes compilation errors introduced by PR #92 (Friends & Challenge) merge:

- **Missing ML Kit dependency**: `SocialScreen.kt` imports `com.google.mlkit.vision.barcode.common.Barcode` which belongs to `com.google.mlkit:barcode-scanning`, separate from the already-included `play-services-code-scanner`. Added `mlkit-barcode-scanning = "17.3.0"` to `libs.versions.toml` and the corresponding `implementation` to `app/build.gradle.kts`.
- **LaunchedEffect outside @Composable scope**: `LaunchedEffect(incomingDeepLink)` was placed inside the `NavHost { }` lambda whose receiver is `NavGraphBuilder` (not a `@Composable` context). Moved it to the `AppNavigation` function body (before `NavHost`), which is a valid `@Composable` context. Logic and behaviour are unchanged.

## Files changed

- `gradle/libs.versions.toml` — add `mlkitBarcode` version + `mlkit-barcode-scanning` library alias
- `app/build.gradle.kts` — add `implementation(libs.mlkit.barcode.scanning)`
- `app/src/main/java/com/cancleeric/dominoblockade/presentation/navigation/AppNavigation.kt` — move `LaunchedEffect` block before `NavHost`

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by cancleeric** [comment]
## CI Fail — compileDebugKotlin 失敗，需修正 ML Kit import 路徑

**Run ID**：24380838029 — Unit Test job FAILED（Lint 仍在跑中）

### 根本原因

`SocialScreen.kt` 的 import 使用了錯誤的包路徑：

```
// 錯誤（不存在於 play-services-code-scanner）
import com.google.android.gms.mlkit.common.MlKitException
import com.google.android.gms.mlkit.vision.codescanner.GmsBarcodeScannerOptions
import com.google.android.gms.mlkit.vision.codescanner.GmsBarcodeScanning
```

`play-services-code-scanner`（`com.google.android.gms:play-services-code-scanner`）的正確類別路徑是：

```
import com.google.mlkit.common.MlKitException
import com.google.mlkit.vision.codescanner.GmsBarcodeScannerOptions
import com.google.mlkit.vision.codescanner.GmsBarcodeScanning
```

注意：`GmsBarcodeScannerOptions`、`GmsBarcodeScanning`、`MlKitException` 全部都在 `com.google.mlkit.*`，不是 `com.google.android.gms.mlkit.*`。

### 第二個錯誤 — delegated property smart cast（line 198）

```kotlin
// bitmap 是 by produceState 的 delegated property，無法直接 smart cast
bitmap = bitmap.asImageBitmap()  // error: Smart cast impossible
```

修法：

```kotlin
val bmp = bitmap  // 先指定到 local val
if (bmp != null) {
    Image(bitmap = bmp.asImageBitmap(), ...)
}
```

### 修法摘要

1. `SocialScreen.kt` 第 46–48 行 import：將 `com.google.android.gms.mlkit.*` 改為 `com.google.mlkit.*`
2. `SocialScreen.kt` 第 196 行附近：`QrSection` composable 中將 `bitmap` 賦值給 local val 再傳入 `Image`
3. `startQrScan` 函式的 `MlKitException` 也需同步修正（第 323 行）

請修正後 push，CI 會自動重跑。
